/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.movies.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Movie service. Represents a row in the &quot;movies_Movie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.training.movies.model.impl.MovieModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.training.movies.model.impl.MovieImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Movie
 * @see com.liferay.training.movies.model.impl.MovieImpl
 * @see com.liferay.training.movies.model.impl.MovieModelImpl
 * @generated
 */
@ProviderType
public interface MovieModel extends BaseModel<Movie>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a movie model instance should use the {@link Movie} interface instead.
	 */

	/**
	 * Returns the primary key of this movie.
	 *
	 * @return the primary key of this movie
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this movie.
	 *
	 * @param primaryKey the primary key of this movie
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this movie.
	 *
	 * @return the uuid of this movie
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this movie.
	 *
	 * @param uuid the uuid of this movie
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the movie ID of this movie.
	 *
	 * @return the movie ID of this movie
	 */
	public long getMovieId();

	/**
	 * Sets the movie ID of this movie.
	 *
	 * @param movieId the movie ID of this movie
	 */
	public void setMovieId(long movieId);

	/**
	 * Returns the group ID of this movie.
	 *
	 * @return the group ID of this movie
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this movie.
	 *
	 * @param groupId the group ID of this movie
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this movie.
	 *
	 * @return the company ID of this movie
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this movie.
	 *
	 * @param companyId the company ID of this movie
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this movie.
	 *
	 * @return the user ID of this movie
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this movie.
	 *
	 * @param userId the user ID of this movie
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this movie.
	 *
	 * @return the user uuid of this movie
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this movie.
	 *
	 * @param userUuid the user uuid of this movie
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this movie.
	 *
	 * @return the create date of this movie
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this movie.
	 *
	 * @param createDate the create date of this movie
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this movie.
	 *
	 * @return the modified date of this movie
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this movie.
	 *
	 * @param modifiedDate the modified date of this movie
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the movie name of this movie.
	 *
	 * @return the movie name of this movie
	 */
	@AutoEscape
	public String getMovieName();

	/**
	 * Sets the movie name of this movie.
	 *
	 * @param movieName the movie name of this movie
	 */
	public void setMovieName(String movieName);

	/**
	 * Returns the description of this movie.
	 *
	 * @return the description of this movie
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this movie.
	 *
	 * @param description the description of this movie
	 */
	public void setDescription(String description);

	/**
	 * Returns the rating of this movie.
	 *
	 * @return the rating of this movie
	 */
	public int getRating();

	/**
	 * Sets the rating of this movie.
	 *
	 * @param rating the rating of this movie
	 */
	public void setRating(int rating);

	/**
	 * Returns the user name of this movie.
	 *
	 * @return the user name of this movie
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this movie.
	 *
	 * @param userName the user name of this movie
	 */
	@Override
	public void setUserName(String userName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Movie movie);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Movie> toCacheModel();

	@Override
	public Movie toEscapedModel();

	@Override
	public Movie toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}