/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.movies.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.liferay.training.movies.model.Movie;
import com.liferay.training.movies.model.MovieModel;
import com.liferay.training.movies.model.MovieSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Movie service. Represents a row in the &quot;movies_Movie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MovieModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MovieImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MovieImpl
 * @see Movie
 * @see MovieModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MovieModelImpl extends BaseModelImpl<Movie> implements MovieModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a movie model instance should use the {@link Movie} interface instead.
	 */
	public static final String TABLE_NAME = "movies_Movie";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "movieId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "movieName", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "rating", Types.INTEGER },
			{ "userName", Types.VARCHAR },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("movieId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("movieName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rating", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table movies_Movie (uuid_ VARCHAR(75) null,movieId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,movieName VARCHAR(75) null,description VARCHAR(75) null,rating INTEGER,userName VARCHAR(75) null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table movies_Movie";
	public static final String ORDER_BY_JPQL = " ORDER BY movie.movieId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY movies_Movie.movieId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.training.movies.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.training.movies.model.Movie"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.training.movies.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.training.movies.model.Movie"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.training.movies.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.training.movies.model.Movie"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long MOVIEID_COLUMN_BITMASK = 4L;
	public static final long MOVIENAME_COLUMN_BITMASK = 8L;
	public static final long RATING_COLUMN_BITMASK = 16L;
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Movie toModel(MovieSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Movie model = new MovieImpl();

		model.setUuid(soapModel.getUuid());
		model.setMovieId(soapModel.getMovieId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMovieName(soapModel.getMovieName());
		model.setDescription(soapModel.getDescription());
		model.setRating(soapModel.getRating());
		model.setUserName(soapModel.getUserName());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Movie> toModels(MovieSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Movie> models = new ArrayList<Movie>(soapModels.length);

		for (MovieSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.training.movies.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.training.movies.model.Movie"));

	public MovieModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _movieId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMovieId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _movieId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Movie.class;
	}

	@Override
	public String getModelClassName() {
		return Movie.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("movieId", getMovieId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("movieName", getMovieName());
		attributes.put("description", getDescription());
		attributes.put("rating", getRating());
		attributes.put("userName", getUserName());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long movieId = (Long)attributes.get("movieId");

		if (movieId != null) {
			setMovieId(movieId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String movieName = (String)attributes.get("movieName");

		if (movieName != null) {
			setMovieName(movieName);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Integer rating = (Integer)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getMovieId() {
		return _movieId;
	}

	@Override
	public void setMovieId(long movieId) {
		_columnBitmask |= MOVIEID_COLUMN_BITMASK;

		if (!_setOriginalMovieId) {
			_setOriginalMovieId = true;

			_originalMovieId = _movieId;
		}

		_movieId = movieId;
	}

	public long getOriginalMovieId() {
		return _originalMovieId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMovieName() {
		if (_movieName == null) {
			return "";
		}
		else {
			return _movieName;
		}
	}

	@Override
	public void setMovieName(String movieName) {
		_columnBitmask |= MOVIENAME_COLUMN_BITMASK;

		if (_originalMovieName == null) {
			_originalMovieName = _movieName;
		}

		_movieName = movieName;
	}

	public String getOriginalMovieName() {
		return GetterUtil.getString(_originalMovieName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getRating() {
		return _rating;
	}

	@Override
	public void setRating(int rating) {
		_columnBitmask |= RATING_COLUMN_BITMASK;

		if (!_setOriginalRating) {
			_setOriginalRating = true;

			_originalRating = _rating;
		}

		_rating = rating;
	}

	public int getOriginalRating() {
		return _originalRating;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Movie.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Movie.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Movie toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Movie)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MovieImpl movieImpl = new MovieImpl();

		movieImpl.setUuid(getUuid());
		movieImpl.setMovieId(getMovieId());
		movieImpl.setGroupId(getGroupId());
		movieImpl.setCompanyId(getCompanyId());
		movieImpl.setUserId(getUserId());
		movieImpl.setCreateDate(getCreateDate());
		movieImpl.setModifiedDate(getModifiedDate());
		movieImpl.setMovieName(getMovieName());
		movieImpl.setDescription(getDescription());
		movieImpl.setRating(getRating());
		movieImpl.setUserName(getUserName());
		movieImpl.setStatus(getStatus());

		movieImpl.resetOriginalValues();

		return movieImpl;
	}

	@Override
	public int compareTo(Movie movie) {
		long primaryKey = movie.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Movie)) {
			return false;
		}

		Movie movie = (Movie)obj;

		long primaryKey = movie.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MovieModelImpl movieModelImpl = this;

		movieModelImpl._originalUuid = movieModelImpl._uuid;

		movieModelImpl._originalMovieId = movieModelImpl._movieId;

		movieModelImpl._setOriginalMovieId = false;

		movieModelImpl._originalGroupId = movieModelImpl._groupId;

		movieModelImpl._setOriginalGroupId = false;

		movieModelImpl._originalCompanyId = movieModelImpl._companyId;

		movieModelImpl._setOriginalCompanyId = false;

		movieModelImpl._setModifiedDate = false;

		movieModelImpl._originalMovieName = movieModelImpl._movieName;

		movieModelImpl._originalRating = movieModelImpl._rating;

		movieModelImpl._setOriginalRating = false;

		movieModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Movie> toCacheModel() {
		MovieCacheModel movieCacheModel = new MovieCacheModel();

		movieCacheModel.uuid = getUuid();

		String uuid = movieCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			movieCacheModel.uuid = null;
		}

		movieCacheModel.movieId = getMovieId();

		movieCacheModel.groupId = getGroupId();

		movieCacheModel.companyId = getCompanyId();

		movieCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			movieCacheModel.createDate = createDate.getTime();
		}
		else {
			movieCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			movieCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			movieCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		movieCacheModel.movieName = getMovieName();

		String movieName = movieCacheModel.movieName;

		if ((movieName != null) && (movieName.length() == 0)) {
			movieCacheModel.movieName = null;
		}

		movieCacheModel.description = getDescription();

		String description = movieCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			movieCacheModel.description = null;
		}

		movieCacheModel.rating = getRating();

		movieCacheModel.userName = getUserName();

		String userName = movieCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			movieCacheModel.userName = null;
		}

		movieCacheModel.status = getStatus();

		return movieCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", movieId=");
		sb.append(getMovieId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", movieName=");
		sb.append(getMovieName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.training.movies.model.Movie");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>movieId</column-name><column-value><![CDATA[");
		sb.append(getMovieId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>movieName</column-name><column-value><![CDATA[");
		sb.append(getMovieName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Movie.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Movie.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _movieId;
	private long _originalMovieId;
	private boolean _setOriginalMovieId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _movieName;
	private String _originalMovieName;
	private String _description;
	private int _rating;
	private int _originalRating;
	private boolean _setOriginalRating;
	private String _userName;
	private int _status;
	private long _columnBitmask;
	private Movie _escapedModel;
}